### PR TITLE
Use UICollectionView rather than AQGridView

### PR DESCRIPTION
**Pull request by sdarlington**
Thought I'd offer this, though I'm not sure you'll want to take it.

Pluses:
- A lot less code
- Better tested grid code (it's part of the OS!)

Cons:
- Don't support iOS5 (without integrating something like [PSTCollectionView](https://github.com/steipete/PSTCollectionView))

### CODE REVIEW

**Comment by ghost** [comment]
That's a great idea. Also, considering that 83% of all iOS data traffic in the USA is from iOS6 devices, the con (no iOS5 support) isn't really an issue at all. I would imagine the statistic is similar and other countries.

Source: http://appleinsider.com/articles/13/02/13/apples-ios-6-now-accounts-for-83-of-all-ios-based-traffic-in-north-america

**Comment by Simbul** [comment]
Hi @sdarlington. I've tried applying this on top of the current `master`. It compiles ok, but I noticed that when you open Baker, the shelf is empty (though it's correctly populated if you refresh it manually).

I've [pushed the merged branch](https://github.com/Simbul/baker/compare/master...sdarlington-uicollectionview) so you can look at it if you want (as I had to solve a couple of minor conflicts).

**Comment by sdarlington** [comment]
The cause was `[self handleRefresh:nil];` being added to the `init` method rather than in `viewDidLoad:` which meant that the UICollectionView wasn't initialised when `handleRefresh:` tried to update it.

Not sure it makes sense to have the refresh in the init method... but still, the refresh method should work even if the grid isn't initialised, so I restructured the use of the block.

**Comment by Simbul** [comment]
Tested the fix and now it works, thanks.

One thing I noticed while testing: the alignment of cells in landscape mode is a bit wrong.

This is how it looks currently in Baker (with some test books):
screen shot 2013-05-25 at 15 41 50

This is how it looks in your branch:
screen shot 2013-05-25 at 15 39 42

Do you think you could fix this as well? :)

**Comment by Simbul** [comment]
In addition, if you do a reintegration merge of Baker `master` in your fork, it should be possible for us to merge the pull request on Github (not strictly necessary, but it makes things easier ;) )

**Comment by folletto** [comment]
This is looking great! Awesome job. :)

**Comment by sdarlington** [comment]
I think the _correct_ thing to do for the formatting is to create a new `UICollectionViewLayout`... but that's rather a lot of code to write and debug that I don't have time for at the moment! So instead, I figured out a way to mess with the frame to give what looks (to my eyes) the same effect.

**Comment by Simbul** [comment]
That was a great contribution, thanks! :+1:

**Comment by ghost** [comment]
Would it be possible to add a storyboard to this custom version of baker in any meaningful way, I am going to make a newsstand app from it? I am a noob when it comes to designing with code and I want to add three things to the UI which I could do with a storyboard...I think. But with code, I dunno. 

1) A popup when tapping issue covers showing more in depth issue information.
2) A library button when you open an issue in the top navigation bar that brings you back to the issues page again.

Any tips on how to do it?

**Comment by sdarlington** [comment]
You can still still design your popup view in a XIB. There's no reason why you can't mix the two styles.

As for the code versus Storyboard/XIB issue, the project really only has a couple of screens so I'm not sure that things would be dramatically easier to understand that way. Whatever the methodology, digging into a large, unfamiliar code base is tricky. Play around. Add a few breakpoints. Make some changes and see what breaks. This pull request was just the (useful) result of me playing around, trying to get familiar with the code base.

**Pull request merged**
