### PR TITLE
Laker-like Navigation

### PR DESCRIPTION
**Pull request by therabidbanana**
Dunno if the Baker team is interested in adding this feature or if it should remain separate, but I pulled together the Navigation bar from Laker Compendium, with a few enhancements to Florian's code:
- LAKER_NAVIGATION constant to turn on and off Laker-style navigation when building a book (so Baker can be distributed with this feature turned off by default)
- LAKER_NAVIGATION_URL is a relative path constant pointing to the expected location for the nav html file from the book root, defaults to inc/navigation.html
- Navigation can be updated by downloaded hpubs (as long as file is in same relative location as the local book)
- Scroll view resizes better when navigation is active
- Navigation properly hides itself on orientation change (so that you don't have to double toggle to get it back)

### CODE REVIEW

**Comment by Simbul** [comment]
We are actively working on this very same feature (though we haven't yet pushed the changes as they are a work in progress). I'll check to see if we can bring in your changes without throwing away the work we've done so far ;)

**Comment by folletto** [comment]
Awesome work! I hope we can merge it easily with the master branch! :)

Well there is a change that we discussed, that is able to improve the overall effectiveness of the Hpub format: instead of "navigation.htm" we were implementing "index.html". This for a few reasons:
- It's already well understood and used on the web
- It specify it's an index, but not necessarily a navigation
- It makes automatically compatible for web reading _any_ Hpub unzipped book
- If the file is there, navigation exists. If the file isn't there, navigation is turned off automatically. ;)

The summary is: a simple change that triggers huge benefits. :)

I'm writing this just to be more transparent - it's my fault, I should have written this discussion we had in our last weekly call - Simbul is already aware of this and he's probably checking this part too when merging. :)

**Comment by therabidbanana** [comment]
That's certainly a more elegant solution than what I went with - I hid the navigation in a subfolder so that it'd be hidden, but obviously a change in the hpub specification would be a much more straightforward solution (all my nav items have to link with a "../" in front of them).  Look forward to seeing those changes. 

This pull request is mainly to go along with another project I'm releasing shortly to allow building a book as a Sinatra app, with a rake task to package up the latest version into an .hpub for easy downloading (so I can use my favorite ruby libraries - HAML and SASS). Thanks for the heads up on the addition of index.html to the hpub specification.

**Comment by folletto** [comment]
That's awesome, please keep us updated also on that front! :)

**Comment by Simbul** [comment]
I've just finished reviewing and testing the commits in the pull request: everything works very well.
The only problem is, when we decided to include the navigation bar in the Baker codebase, we defined some specifications that are conflicting with this implementation. Mainly, the statusbar should still be present and the navigation bar should appear/disappear along with it and have the same behavior (e.g. disappear when the user interacts with the application in any way).
In addition, we specified the index.html file as illustrated above by Folletto and we are implementing the navigation bar as a separate class, to avoid adding any more clutter to RootViewController.
All in all, these considerations would make merging this pull request impractical.
I'm sorry we did not communicate early enough what we had decided about the navigation bar: that would have prevented wasting some very good work.
We'll try to release the navigation bar code as soon as possible. If you then decided you wanted to improve on that, you'd be more than welcome :)

**Comment by therabidbanana** [comment]
No worries - it's been a while since I did any ObjC, was good to get some practice. Look forward to seeing the implementation you guys are working on.

**Pull request closed without merging**
