### PR TITLE
Landscape book orientation (+ CSS media query)

### PR DESCRIPTION
**Pull request by svdgraaf**
I'm working on orientation change and we can now support media queries for css (as UIWebView supports it natively).

Awesomeness! :D

### CODE REVIEW

**Comment by Xm4s** [comment]
Wow! You were really fast on this one :D

Thank you for your help, now give us some times to test and review your code, we'll give you a feedback as soon as possible.

**Comment by svdgraaf** [comment]
Sure, let me know if I need to change anything or anything is not clear.

**Comment by segundoseis** [comment]
hello svdgraaf!
How could I do to make the page numbers are centered instead of deleting it?
thank you very much!

**Comment by Xm4s** [comment]
Hi svdgraaf!

I have reviewed your code and rotation works like a charm :D 
But there are some things that needs to be fixed in order to merge your patch on our master branch.

First of all the compiler returned me 3 warnings: while they are not critical at all, they have to be fixed for a clean release. I think you forgot to declare the function initTapHandlers in the RootViewController header file and that is causing the warnings, try have a look on that.

Second we have the page number: we can't remove them completely because they are a precious reference for the user, to show him where he is and of course where is he going (expecially now that multiple taps/swipes to jump around pages are available). I know that having to rewrite them on the UIScrollView in case of rotation may not be very fun, but it has to be done :)

Then the page reloading on rotation: while is perfectly correct it's not very good as it is. Could you please try adding a fade out of the page before the reloading to make the transition more smooth? I think that should do the trick.

And finally the forced portrait mode on application startup: we think that the application should check the available orientation of the book and the orientation of the device to present the views of the expected size. We were thinking about putting a flag with 3 possibile value (like for example "portrait", "landscape" and "both") to define which book templates are available and handle the three possible cases:
- case 1, flag == "portrait": app forces protrait mode on startup and blocks rotation to landscape.
- case 2, flag == "landscape": app forces landscape mode on startup and blocks rotation to portrait.
- case 3, flag == "both": app checks the device orientation and presents the correct views, both on startup and on orientation change.
  Of course this flag will have to be set manually in the code by the publishers, at least untill the definition and implementation of a proper HPub standard. I've seen your code, maybe you can start by making a new function out of the instructions you use to handle rotation and then call it where and when you need it.

Well, that's it. I know it seems like a lot of work, but we think that all those points have to be clear in order to add a polish rotation support to the framework. We really appreciate your help on the matter so we would like to know if you're willing to take on these tasks and what you think about them because, as i said before, you already are on the right track and your help and opinion is really valuable to us.

Thank you for the hard work so far, we'll be waiting for your feedback :D

**Comment by svdgraaf** [comment]
sure, I'll take a look at it and fix those issues. The pagenumbers need quite a bit of refactoring I think, but I'll see what happens.

I'll close this pull request for now

**Comment by folletto** [comment]
I think you can keep open the pull request and incrementally improve it until it's ready for merging. It's quite a nice feature of GitHub. ;)

**Comment by Simbul** [comment]
Yup, you can add further commits to a pull request.
See this document:
http://help.github.com/pull-requests/#pull_request_discussion

**Comment by svdgraaf** [comment]
ah, great :)

**Comment by svdgraaf** [comment]
Hmmm, too bad we removed the xib's from the project, I need to put in a lot of code just to get the orientation changes fixed, which we could get out of the box if we used the xib's :(

**Comment by folletto** [comment]
Could you explain it a bit more? We could always put them back. ;)

**Comment by svdgraaf** [comment]
Ok, as as far as I understand right now, the problem is that because of the extension of the UIWindow, the new source window (in this case the InterceptorWindow), needs to handle the orientation changes of the device. I can (probably) add all the code in there, but it would take quite some time, whilst we would get it for free using the default UIWindow.

But perhaps I'm completely off, as I'm relatively new to obj-c. I'll put in some more time and see if I can get it working without (or get a solution with the xib's).

**Comment by Simbul** [comment]
I'll have to look into this, but it seems unlikely that the problem is with the extension: InterceptorWindow is a subclass of UIWindow, so it should inherit all its methods (orientation management included).

What exactly is missing for your code to work?

**Comment by svdgraaf** [comment]
The extending stuff is what I figured too, that's what makes it so weird :)

I just committed what should be working, but isn't, perhaps you can take a look at it? The didRotateFromInterfaceOrientation in RootViewController doesn't get called anymore, while the shouldAutorotateToInterfaceOrientation _does_ get called in the RootViewController, which doesn't make sense to me.

I tried adding a listener for orientation changes, which worked, but the full application doesn't get rotated, it just notices that the device is rotated :(

**Comment by svdgraaf** [comment]
Ok, I think I got it, the initWithNibName method probably appends some logic for implementing the rotation of the views. I have a somewhat working version right now, but it does use the xib's, I'll clean it up and push it.

**Comment by Simbul** [comment]
Yeah, I was thinking it had to be some initialization problem, but I haven't had time to sort it out yet.
If you've got it working, all the better ;)

**Comment by svdgraaf** [comment]
Ok, everything is in place now for it to work, except for the IntercepterWindow Tap functionality. I'll take another look at that tomorrow, but I'm not sure if I can figure that out.

Other than that: rotating is awesome! :D

**Comment by svdgraaf** [comment]
ok, everything should be in place now for a merge, can anyone check my version and let me know if anything needs work?

**Comment by ilovemac** [comment]
i will test it just now!
give me some mins

**Comment by segundoseis** [comment]
hello @svdgraaf
I'm testing your app svdgraaf-baker-a376d9d, the app have 40 html/pages?

**Comment by svdgraaf** [comment]
errr? I guess you are experiencing the same bug I was having ;) The problem is in the settigns which are saved from a previous session, in other words -> it wants to load a pagenumber of a previous build which you ran, but it can't find it.

I'll solve the bug, it needs to be fixed anyway :)

**Comment by svdgraaf** [comment]
Try again! :)

**Comment by segundoseis** [comment]
is true!
is working properly! :-)

**Comment by svdgraaf** [comment]
awesome! :D

**Comment by segundoseis** [comment]
but I could not see it working on the iphone. Adaptation was done right?

**Comment by svdgraaf** [comment]
The code is in, we only need to add a build for the iphone version, I haven't worked on that yet, this is just the rotation changes. Let's put that in a separate changeset as this one is getting pretty big already :)

**Comment by segundoseis** [comment]
sorry! was my problem when compiling.
The application works fine on the iphone and only need a few adjustments in htmls for detecting different sizes and load other css. ;-) 
I'll test...  txs

nice work!!

**Comment by svdgraaf** [comment]
cool! can you point me how to setup compiling so it will run on an iphone? I want to test it too :)

**Comment by svdgraaf** [comment]
never mind, got it! http://stackoverflow.com/questions/2413948/setting-xcodes-target-to-iphone-not-ipad

**Comment by svdgraaf** [comment]
Yeah, changing the css width to auto fixes the build for the iphone, which is awesome, because it works even without testing it! :D

If we can pull this into the main branch, we could perhaps create a 1.1 release of it :)

**Comment by segundoseis** [comment]
1 - in Xcode > Double click in Baker project.
You have to select in Depluyment/Targeted Device Family  =  iphone/ipad

2 - in Xcode, open the select under the close and minimize buttons.
Put simulator and the "Active executable" that you want ;-)

-> Build and Run.

**Comment by segundoseis** [comment]
Do you think that something like this?

```
    <link rel="stylesheet" media="screen and (max-device-width: 320px) and (orientation:portrait)" href="css/iphone-portrait.css"> 
    <link rel="stylesheet" media="screen and (max-device-width: 480px) and (orientation:landscape)" href="css/iphone-landscape.css">

    <link rel="stylesheet" media="screen and (min-device-width: 481px) and (max-device-width: 1024px) and (orientation:portrait)" href="css/ipad-portrait.css"> 
    <link rel="stylesheet" media="screen and (min-device-width: 481px) and (max-device-width: 1024px) and (orientation:landscape)" href="css/ipad-landscape.css">

    <link rel="stylesheet" media="screen and (min-device-width: 1025px)" href="css/ipad-landscape.css"> 
```

**Comment by svdgraaf** [comment]
Yep, that should do the trick :)

**Comment by segundoseis** [comment]
you can put the same css with different font colors in the body for test  ;-)

body {
    color: blue;
}

(#)wrapper {
    width: auto;
    margin: 10px;
}

**Comment by folletto** [comment]
Just a quick note: amazing work. :)

Tomorrow I'll test out everything. :)

**Comment by Xm4s** [comment]
Hi svdgraff!

I've quickly reviewed your code and it'works pretty well, just a few notes:
- I can't seems to find the check on the available orientations of the book (the one we discussed before)
- At every rotation you keep adding tapHandlers without removing the older ones. Maybe you should have some kind of reset function, which remove all the old spinners, page numbers and tapHandlers, called before the rotation is handled (inside the "shouldAutorotateToInterfaceOrientation" may be a good point); also at the same time you can try add a fade out animation to the current page, to smooth the rotation and reload transition a bit.
- I really don't think xib files are necessary (well, I try to remove them and everything worked just fine :P)

Well that's all, as I stated before I just had a quick look at your code. These notes are both for you and for Folletto, who will provide a deeper and better review as soon as he can.

In the meantime let me once again thank you for your help on this task, you really are a hard worker and you deserve our praise for your support.

So let's keep up the good work together :D

**Comment by svdgraaf** [comment]
Awesome, I'll take a look at those points, if Folletto can find more, let me know :)

**Comment by svdgraaf** [comment]
Ok, the taphandlers are fixed, and the xib's are removed.

I'm not sure about the rotation check, I think that is one of the things that need to be added to the meta file. Currently, the uiWebView just renders the html again. If you design the css correctly, it will just center your html file for you, so the user is already in control. If we add the meta file, we can add that to the shouldAutorotateToInterfaceOrientation method.

**Comment by jeffehobbs** [comment]
I have no input on this other than to say: Adding these features is really cool!

**Comment by ilovemac** [comment]
All this wonderfull news sounds good!!...i will test as soon !!! :)

**Comment by svdgraaf** [comment]
ok, since we lost quite a bit since the downtime. I think the status quo is that I need to test this on a real device to figure what is wrong with the sizing, and why it differs from the simulator :(

**Comment by folletto** [comment]
Argh. Well.. yes.

**Comment by svdgraaf** [comment]
Great, I had a quick call with Apple today, I should be up and running with my dev account somewhere within the next 24 hours, woohoo!

**Comment by svdgraaf** [comment]
great, my dev account is enabled, I can see the problem with the rotation now, it's really, really weird. Anyway, I think it's not that hard to fix, I'll get cracking!

**Comment by svdgraaf** [comment]
Fixed! :D

Let me know if any other issues arise, I would like to have this in asap, as I want to get working on the zip support :)

**Comment by ilovemac** [comment]
i'm downloading it ! :)
keep in touch! :D

**Comment by ilovemac** [comment]
ooohhh yes!!....Now it's time to rock'n'roll with css :))

**Comment by ilovemac** [comment]
mmhh...link to other page don't work??

**Comment by svdgraaf** [comment]
@ilovemac, what do you mean? The packaged default book works over here?

**Comment by ilovemac** [comment]
mmh...really..i have not try with it...but with my book..:(

**Comment by ilovemac** [comment]
seems to be  a jquery problem....mmmm..if i remove from the page of the book..it's back to work!

**Comment by svdgraaf** [comment]
Awesome! Anyone else who can approve? :)

**Comment by svdgraaf** [comment]
Can anyone check this pull request again? I would be nice to get it merged with Master :)

**Comment by Xm4s** [comment]
Hi! 

We'll test your code as soon as possible.
For now, as always, thank you for your support :)

**Comment by svdgraaf** [comment]
Thanks a bunch mates, keep up the progress and discussions :)

**Comment by segundoseis** [comment]
I received my Apple developer account minutes ago.
In the evening I will test in the devices (ipad/iphone) 
:)

**Comment by svdgraaf** [comment]
awesome, people are pretty excited over the possibilities over here :)

**Comment by jeffehobbs** [comment]
I see a brief, almost imperceptible flash of the content of the previous page when I swipe between pages. (iOS 4.2 iPad).

**Comment by svdgraaf** [comment]
Yeah, I noticed that too, it gets worse if you build larger pages with more content. But that bug is also in the master branch, let's fix it there :)

**Comment by segundoseis** [comment]
hello @svdgraaf
Even I could not test in ipad because I'm downloading the Xcode to use with ios 4.2
In iphone there is something wrong in the rotation. I posted a short video in order to better appreciate what I mean.
You will see that by rotating, the css change correctly (red and blue) but makes a blink.
http://www.segundoseis.com/IMG_0489.MOV

book with css for test
http://www.segundoseis.com/book_w_css.zip

**Comment by svdgraaf** [comment]
Yeah, I'm not sure whether this is an issue or a feature :) 
uiwebview needs to do a proper reload to get the new size of the view. I don't know how to fix it at the moment, perhaps someone else can take a look at it? I don't have any time to check it out tomorrow, perhaps on friday. Then again, I think we can pull this into the master regardless of this "issue" ;)

**Comment by ilovemac** [comment]
@svdgraaf: if u can, answer to my private question :)

**Comment by segundoseis** [comment]
I saw something in ipad 4.2
- select some page (example 5) then change the view rotating fast.. 3 or 4 times. You will see that the page does not charged... Number and load icon forever. If you change to the next page and back works again.

**Comment by svdgraaf** [comment]
Fix for the flashes is in, it will only flash once now, and only if the app was started in landscape mode, and you are rotating to portrait, after that, it will work without flashing. If the app was started in Portrait, it will not show any flash.

And as a bonus: the rotating is a lot faster now too! :D

**Comment by svdgraaf** [comment]
@segundoseis I tried to reproduce your bug with the fast rotating of the device, but I can't reproduce it (or I'm getting old, and can't rotate as fast as I should ;)), it could also be that it's fixed because of my last bugfix for the rotation.

Could you check again? Thanks!

**Comment by segundoseis** [comment]
hello @svdgraaf
Do not say anything about getting older that next Wednesday is my birthday. :-S

I posted a short video about my comments for the rotation. 
http://www.segundoseis.com/IMG_1436.MOV

Other thing that you can see in the video is when getting to the bottom of the page, the button makes a rare move with the html.

I will test the new version after dinner :)

**Comment by segundoseis** [comment]
seems that the new version has no longer the problem by rotating the video showing.
There are times when in landscape mode you can see the content as portrait, with the right button area in the screen middle.. maybe is my book.. I will test more

There are only a couple of things that were reported:
- rare movement in Html with the lower button.
- displayed previous html for a moment prior to the fade In page

**Comment by folletto** [comment]
I've just tested and I got a few issues remaining:
1. The white background is now the textured background seen when you go out of scroll in some situations, is it for debug reasons?
2. Quite every time I do this: portrait, then switching landscape, then moving on the next page, then switching portrait again the webview stays sized as landscape

Forcing the orientaton via plist works like a charm, I think that's ok. :)

**Comment by segundoseis** [comment]
The textured background is the last svdgraff modificated version ;-)

**Comment by folletto** [comment]
Oh ok, I'll wait then. :)

**Comment by ghost** [comment]
When do you plan to merge that pull request to master branch?

**Comment by folletto** [comment]
I think that the good answer is going to be: "when it works". :)
I hope we are able to do that before christmas, but it's really something that involves the developer of this branch and the subsequent merge, so we'll see.

If you want to help him fixing the last bugs it could be also a good way to move that date early. ;)

**Comment by svdgraaf** [comment]
hi!

Yeah, it's almost finished, just haven't found any time to get the last change out. It should be a minor fix, so if anyone is willing to look into it: awesome, send me a pull request on my local branch :)

**Comment by folletto** [comment]
Great!

I'm a bit busy too, so for now I'll wait. ;)

**Comment by yu12** [comment]
Baker is really a great idea, simple yet elegant, and it has a lot of potential!!  I've tried this new feature, it worked great! a millions thanks to you guys!!!

**Comment by MacBoy** [comment]
Many of us intend on using Baker for magazines, portfolios, product catalogs, etc.

for those scenarios, the Landscape orientation is very important.

Please make the provided fixes be a part of the main branch.

Thank you for such a nice framework.  It has many possibilities after a few fixes and features are completed.

Thank you!!!

**Comment by folletto** [comment]
We know it's priority, we'll merge once the branch is completed. :)

**Comment by aldriq** [comment]
Excellent work going on here, I must say!

I have a quick question hopefully related to these new options. The book I'm currently working on is pretty standard typographically speaking, except (of course there is always one 'except') in one of the appendices there is a large -wide- table. If I was approaching this on a paper book the first think that came to mind was one of these unfoldable pages you'd get in old atlases and encyclopedias, but that seems tricky to achieve in the current framework. 

So an easier solution could be perhaps to force the page to horizontal orientation. Would that be possible with the new options?

**Comment by folletto** [comment]
Horizontal for just one page? Well, it's tricky, because I think we are going to achieve "whole book" orientation not single page one. However, did you try placing the whole table inside? When you exceed the page size the book is still browseable, just you have to scroll right first.

**Comment by aldriq** [comment]
Yes, just for one page. I haven't tried the table in a normal page yet, I thought it would just disappear beyond the page limit, but if it lets you scroll then that's fine for me, a much cleaner solution.

**Comment by magix** [comment]
Cool  svdgraaf . next add page cache ..

**Comment by folletto** [comment]
Tonight we did a joint session and moved this feature ahead. Now we are working on a different tree from master, autorotate, because it's not functional yet, many bugs to fix ahead of us but the core functionality is there, taken from svdgraaf's branch.

**Comment by svdgraaf** [comment]
awesome! I haven't had any time to work on this whatsoever :(

**Comment by k8fisher** [comment]
can i confirm how one calls the orientation methods described above? Ive been looking at an example on css3 suggested by one of the group members at http://www.1stwebdesigner.com/css/how-to-use-css3-orientation-media-queries/

When I run the demo from the page on an ipad it works, however when I run code following the same pattern within xcode/baker the code doesnt work.

Should I just be utilising the baker methods discussed above?

Sorry m new to the thread/baker framework.

Kate

**Comment by folletto** [comment]
Uhm I don't quite understand what's the problem about. Could you open a new issue and describe it a little more? :)

Thanks! :)

**Comment by k8fisher** [comment]
Hi Folletto, I guess Im just a little behind things. Im familiar with some programmatic struff (original training with unix based languages etc.) Anyway Im seeing there being classes / programmatic bits within the present build of the baker framework. I just dont understand the crossover between the html5 documents I create to sit within the baker framework object and the classes etc / bits within the directory structure. I need to log up on css3 as Im more familiar with css2. I guess thats really the heart of it understanding where the classes bits discussed above lie in relation to the html5 code that my book sits within. E.g. if I want my book to switch orientation / add navigation to the scenario do I call programmatic elements from within baker, or is it something else I interact with.

As mentioned before  I dont understand the relationship between the entiries html5, classes of baker, webkit etc.

Any assistance would be most welcome as I have programmatic experience Im just in a whole other environment. Is there a book which might help me get up and running with this thing as Im trying to find my bearings atm.

Much appreciated.

Kate

**Comment by folletto** [comment]
Ok, but could you open a specific issue? ;)

**Pull request closed without merging**
