### PR TITLE
Implementation of bookmarks, the HTML5 way (issue #104)

### PR DESCRIPTION
**Pull request by nurtext**
Altered the example book with an example implementation for bookmarks. Pure HTML5/JS/WebSQL.
Have fun! :)

Demo: http://www.youtube.com/watch?v=Uask5OsCd6k&hd=1

### CODE REVIEW

**Comment by tstegart** [comment]
Holy cows that is AWESOME. Does it work across books? For example, can I have one bookmark page and a user can see all the articles they have bookmarked across all the issues they have ever read? Would there be a way to dim the bookmarks that are in issues not currently on the device?

**Comment by nurtext** [comment]
Should be possible, but I didn't tested it… but you could easily setup a test scenario.

**Comment by Simbul** [comment]
Pretty cool, kudos!

Before we can merge this, I think we should trim down the code that needs to be included in each page. It would be ideal if we could add just a single line (the inclusion of a single JS file that takes care of the listener initialisation).
By the same token, it should be possible to have the initialisation JS add the `bookmark` div to the DOM (as it is `position: fixed` anyway, it shouldn't matter where it sits in the DOM tree).

The other issue I have is, I want to make sure the image used to represent the bookmark is compatible with our license and can be included in Baker with no restrictions. The PNG included in the pull request looks suspiciously similar to the one in iBooks, which I don't think would fit the bill ;)

As a last comment: this wouldn't prevent us from merging your code, but it would be nice if it used [Local Storage](http://diveintohtml5.info/storage.html) instead of Web SQL Database, which is [officially deprecated](http://dev.w3.org/html5/webdatabase/#status-of-this-document) by the W3C :)

**Comment by nurtext** [comment]
Thanks @Simbul. Of course I did take the bookmark images from iBooks, didn't had time to create it on my own. Rewrite shouldn't be a big deal, but using LocalStorage isn't possible as far as I know. LocalStorage was designed for single documents and doesn't work on multiple documents (html files). Because of this restriction I decided to use WebSQL. Didn't heard anything about W3C dropping support for it… :-(

**Comment by folletto** [comment]
LocalStorage should be usable: see Issue #198 for a user using it to perform another task (plus the usual Mozilla documentation: https://developer.mozilla.org/en/DOM/Storage)

As far as I got too, the session should disappear when the page changes, but for some reason (maybe I'm missing something) that's not the case for Baker books. But it might work only between page and index and not between one page and another. But I'd give it a try. ;)

**Comment by nurtext** [comment]
I'll give it a try, thanks @folletto

**Comment by atelier7** [comment]
Hi, just discovered Baker, quite amazing...I'm very interested in trying out local storage,this was pulled from iBooks a while back.  Watched the video nurtext, thank you.  Is there code I can play with, the community entry said code included but I'm new to github and not sure if I'm missing the obvious here  re: where I can down load it?

**Comment by tstegart** [comment]
The links to download the code are on the main page (https://github.com/Simbul/baker) right underneath the link to Baker's website. Look for the big "ZIP" button.

**Comment by Simbul** [comment]
Hi @nurtext, do you have an update on the issues that were still open?

**Comment by Simbul** [comment]
Closing as inactive.

**Pull request closed without merging**
