### PR TITLE
Open a local file in the modal view

### PR DESCRIPTION
**Pull request by benoitchantre**
Useful if you have some local documents (html, pdf, doc, ...) related to the content of your book.

When you open a local file in the modal view, the action button is not shown.

Please note that i'm not familiar with Objective-C nor a professional developer, I hope that it's not too bad written :)

Update: you can also open a local html document in the modal view

### CODE REVIEW

**Comment by benoitchantre** [comment]
@folletto Any feedback would be appreciated.

**Comment by folletto** [comment]
I'm sorry for this, but we didn't have time yet.

**Comment by benoitchantre** [comment]
The reload button is displayed in the modal view for remote files only.

**Comment by benoitchantre** [comment]
Submitted to the new repository.

**Pull request closed without merging**
