### PR TITLE
Added MessageUI framework and URI detection for mailto links to allow in-app sending of mails

### PR DESCRIPTION
**Pull request by nurtext**
All examples below will open the MFMailCompose view:

``` html
<a href="mailto:user@example.com">Send mail</a>
<a href="mailto:user@example.com?subject=Hello%20World">Send mail with subject</a>
<a href="mailto:user@example.com?subject=Hello%20World&body=Foo%20Bar">Send mail with subject and body</a>
```

### CODE REVIEW

**Comment by folletto** [comment]
This looks excellent! Give us time to test it and I think that it will be merged immediately. :D

**Comment by Xm4s** [comment]
This is a really nice improvement, thank you!
Merging right now ...

**Comment by folletto** [comment]
Great! Thank you :D

**Comment by nurtext** [comment]
Superb :)
We should update the wiki though…

Edit: done

**Comment by folletto** [comment]
Excellent, thank you so much. :)

**Pull request merged**
