### PR TITLE
Fixes issue #584.

### PR DESCRIPTION
**Pull request by buildc0de**

### CODE REVIEW

**Comment by Simbul** [comment]
We just tested this. The code is definitely on the right track, but I've noticed that, after you reopen the book from Newsstand, a small grey 20px tall rectangle appears at the bottom of the page.

iOS Simulator Screen shot 4 Feb 2013 22 43 02

Do you get the same?

**Comment by buildc0de** [comment]
~~How interesting. I did see this artefact while working on the issue, but not in the final version of the fix. I just played with 5.x and 6.x and don't seem to be able to reproduce. Do let me know your steps and I will look into this further :-)~~

Never mind, my scrolling was off a bit and I do see it now :-) Will investigate further...

**Comment by buildc0de** [comment]
Been playing with this... The rectangle fix is easy, but it revealed another strange issue with indexScrollView, where it gets resized if indexView is not hidden on entering background. Can't quite wrap my head around this one yet :-)

**Comment by benoitchantre** [comment]
@waywalker: I can't replicate the issue with your fix applied.
Is the "strange issue with indexScrollView" still relevant after your re-implementation?

Thanks for this fix.

**Comment by buildc0de** [comment]
The "strange issue with indexScrollView" did get fixed in the latest implementation as well :) viewDidLayoutSubviews  seems to work like a charm and I found no other artifacts in my testing.

**Comment by aspek** [comment]
So, this problem still happen. #753

**Comment by benoitchantre** [comment]
@aspek: did you applied the fix proposed by waywalker?
If you didn't applied it manually, that's normal that you can reproduce the issue, this fix is not merged in the master branch at the moment.

From my side, I'm not able to reproduce the issue after applying the fix.

**Comment by aspek** [comment]
No, Because my "baker"  It is a newer version look like it have a  bit different code.

OK. but it's work now. Thanks! @benoitchantre  and waywalker.

**Pull request merged**
