### PR TITLE
Added reload button to the modal view

### PR DESCRIPTION
**Pull request by benoitchantre**
Here's the reload button feature.
The button is disabeld until the page is loaded.

The icon comes from [Entypo](http://www.entypo.com).

You can test it with _A Study in Scarlet_: there's a link to the Baker Framework website in the first page.

### CODE REVIEW

**Comment by benoitchantre** [comment]
If there's a way to use a system icon, it would be better.

**Comment by benoitchantre** [comment]
Updated to use the system icon.
The color of the icon is not yet defined. It will be added when #1137 will be merged.

**Comment by folletto** [comment]
Thanks :)

**Comment by benoitchantre** [comment]
You're welcome.

**Pull request merged**
