### PR TITLE
move IndexViewController init from init to initBook to solve book index-height & index-width problem

### PR DESCRIPTION
**Pull request by zenz**
In the original design, baker create the IndexViewController in RootViewController's init method.
But this made the reading of the -baker-index-height & -baker-index-width no effect while loading another book.
(and only fix after kill and relaunch baker).

With this modification, now baker can handle -baker-index-height & -baker-index-width correctly.

### CODE REVIEW

**Comment by zenz** [comment]
Actually, in this case we can do more clean up for IndexViewController.h & IndexViewController.m, because we don't need this model to detect is the index belongs to bundleBook or documentBook, it's only processing every books index page.

**Comment by zenz** [comment]
Sorry to forgot removing the conflict while sync. and all solve now.

**Comment by Simbul** [comment]
Thanks for fixing this!
Unfortunately the commits are not very clean and merging them like this would pollute the repo history a bit.

Do you think you could submit another pull request with the same fix? An ideal pull request would only contain changes to the lines that you had to edit. If you look at the current diff, there are a lot of changes that - I assume - are due to your editor changing the indentation for some blocks of code.
In addition, this would get rid of the commit with the merge conflict ;)

If you can do that, we'll be happy to test it and include it in our `master` branch.

**Comment by zenz** [comment]
Hi, Simbul! good day!
because I'm not so familiar with Github. that's the reason why in the first time I got conflict version.(long time not sync)
I don't know if I can delete my repo and re-fork from master branch of baker or not. I will try to find out the solution.

**Comment by zenz** [comment]
I still don't know how to make it work. but I have refork the master branch from Simbul/baker and commit the changes. I think you can see the difference clean and clear now. no need to merge the request. just see the difference.

**Comment by zenz** [comment]
I think I have made a clean pull request. so close this one.

**Pull request closed without merging**
