### PR TITLE
Two small changes: JSONKit + Retina Screenshots

### PR DESCRIPTION
**Pull request by zenz**
1. replace TouchJSON with JSONKit.
2. add support for capturing retina display screenshots.

### CODE REVIEW

**Comment by folletto** [comment]
A-W-E-S-O-M-E-!

We'll check! :D

**Comment by folletto** [comment]
Note: this refers to Issue #239 and #237.

**Comment by Xm4s** [comment]
Hi!

We have reviewed the code and all seems nice :)
We accept this pull merge: the retina screenshots work without any problems on iPhone 4+ and [JSONKit](https://github.com/johnezang/JSONKit/) seems to be considerably faster than TouchJSON :P

Thank you for your hard works, we really appreciate your effort to improve Baker :D

This closes #239

**Comment by zenz** [comment]
Thank you Xm4s!
Did you find out the reason for ghost screenshot while switch books in issue #229?

**Pull request merged**
