### PR TITLE
Separate publication manifest for testing and production

### PR DESCRIPTION
**Pull request by freney**
If the app is built in DEBUG mode, use an alternative Shelf Manifest URL.

This is required once you've got your app published on the store to test & proof-read new issues. Place them first in the testing publication, then once they pass QA, insert them into the production publication for the rest of the world to see.

(NB: if all issues in this testing publication are free, checking through Apple is bypassed and you don't need to create new records in iTunes Connect.)

### CODE REVIEW

**Comment by freney** [comment]
Note that this works equally well using MagRocket:

```
#undef NEWSSTAND_MANIFEST_URL
#define NEWSSTAND_MANIFEST_URL @"http://example.com/issues/:app_id-Test/:user_id"
```

Then create a Publication called `com.producer.appID-Test` and insert some new issues.

**Comment by folletto** [comment]
I'm not entirely sure about this: seems easy to add if you need it, and easy to forget you setup that flag thus leading to some publication issue. To understand how it works: how is your workflow? :)

**Comment by freney** [comment]
The idea is that you _don't need to remember_ to change when you switch to the production version.

I'll give you a couple of hypotheticals so you can get my reasoning. Both examples will start with MyApp version 1.2, so you've already got the app approved and in the store.
(Admittedly, it's slightly more complicated to set everything up initially, as you need to initialise 2 manifest URL versions, or 2 publications in MagRocket, or whatever else you use.)

Current Baker workflow:
1) Change publication manifest URL to a test version (so that new features/new issues/etc. aren't released to your customers before they're ready).
2) Develop, develop, develop.
3) Change publication manifest back to the production version
4) Build production version & submit app.
5) Repeat.

Step 3 there is absolutely critical, and is the sort of thing I would easily forget, since my test app is working so well at that point. 

If you do forget to change it, app review won't pick up there's a problem either, since you've got good data in there to allow you to test. When it gets released, suddenly everyone gets switched from the production issues they were using to your testing server, which may or may not be a big problem.

My proposed DEBUG flag workflow:
1) Any app built as a debug build in Xcode uses the testing manifest URL (so that new features/new issues/etc. aren't released to your customers before they're ready).
2) Develop, develop, develop.

4) Build production version & submit app.
5) Repeat.

There's no step 3 in this version, as you don't need to go and manually change anything before submission. If the DEBUG flag isn't set, my additional lines of code effectively disappear, and Baker uses the production URL.

Hope that makes sense.

Sam.

**Comment by folletto** [comment]
Yes, I follow the reasoning. Let's see. What happens if a user just wants to use a single URL? Is there a way to make it, by default, not change the current workflow (i.e., for example making the debug block identical to the other URL) and to use it only if you want to use it?

**Comment by freney** [comment]
Seems fine to me.

**Comment by folletto** [comment]
Could you elaborate? :D

It seems to me right now that the DEBUG flag is setup by default from Xcode, and thus any user that wants to use Baker with this change will have to deal with both the parameters (the debug and the standard one). This is in a sense an additional complexity for users that don't want to deal with it. (sorry if I'm assuming something wrong, but I can't test it now).

So: I think the patch will be fine if we can have the debug URL to kick in (and be setup, used, etc) only if you actually want to do it, and if you don't, you can ignore totally that declaration.

**Comment by freney** [comment]
Yes, you're right, it's additional complexity, especially for starting out.
And I agree: it's an option for those who want it. Perhaps have it commented out by default, so advanced users can easily see what it does and turn it on, but those who don't want it won't get bitten by incorrectly setting up the different URLs.

**Comment by folletto** [comment]
Thanks for the clarification. Ok, so you reckon that commenting it out might be the best way to do it?

**Comment by freney** [comment]
Yes, I think so. That's the simplest way to get started, and the patch is aimed at people who already have an app in the store.

**Comment by folletto** [comment]
Ok, thanks! :D

**Comment by nin9creative** [comment]
I also created another issue - similar to this.  For MagRocket it might be easier to just allow Baker to pass along a parameter indicating which environment Baker is currently hitting (debug/sandbox or production).  Then some logic could be done on the server side with regards to pending issues in development / receipt validation etc.

https://github.com/Simbul/baker/issues/1017

**Comment by folletto** [comment]
That might be a good alternative solution: instead of having Baker do the json switch, we have the server doing it. Makes sense to me. Opinions?

**Comment by freney** [comment]
I think it probably depends on how it's done. As it's stated here, it might be increasingly difficult to use Baker apart from Magrocket as the back end. Again, thinking of the simplest solution for starting out: you want a JSON shelf file, a set of images, and a set of zip files. If it's all free, then you don't need anything other than a directory visible on the web. Once you start requiring additional numbers of parameters, then it's becoming a higher bar for new entries.

Now that might be ok in the long run, but I thought it's worth raising. I guess it's a policy decision on the part of Baker: do you do simple network stuff (while allowing complexity), but focus on the client app, or do you build in more complex requirements for a partner project (e.g. MagRocket)?

(This might all end up being pretty academic, as it seems that most people doing complicated things _are_ using MagRocket, because it's awesome.)

**Comment by folletto** [comment]
I agree, that's one thing that I was thinking of. I think that if you need a functionality to split two jsons, you're likely down the road of using or being able to use a simple conditional server-side. Plus, it's also a feature that any server (btw we have two backends out there at the moment – MagRocket and Newsstand DIY – and one incoming – Magboy, plus a few proprietary ones) will implement at some point... that's why I'm wondering if that could be something that we could just pass to the server and let it be. :)

Not 100% sure tho, that's why I wanted to hear other opinions. :)

**Comment by nin9creative** [comment]
Is Magboy from Tope @ appdesignvault?

Andrew

**Comment by folletto** [comment]
http://www.magboy.co/ :)

**Comment by tekdope** [comment]
Well i'm not sure i will trust this since after two clicks it gives me access to all users account...
http://www.magboy.co/users

**Comment by nin9creative** [comment]
Well it is just a beta right?  lol

Regards,
Andrew

**Comment by tekdope** [comment]
Indeed! lol

**Comment by Simbul** [comment]
Hi @freney. Thanks for submitting the pull request. In the end we went with the solution @nin9creative was suggesting in #1017, so it wouldn't make sense to merge this in, but your contribution to the discussion - and the use of the `DEBUG` directive - were extremely valuable.

In passing, the parameter can be interpolated in a URL, so:

``` objc
#define NEWSSTAND_MANIFEST_URL @"http://example.com/:environment/issues/:app_id/:user_id"
```

would result in something like

```
http://example.com/debug/issues/com.example.MyMagazine/8AD5CCA3-632E-4689-A309-F4D827C3F00B
```

**Comment by freney** [comment]
No worries.

**Pull request closed without merging**
