### PR TITLE
Async networking

### PR DESCRIPTION
**Pull request by sdarlington**
Don't block the main thread making network calls. A patch for Issue #787.

This works as far as I can tell but I've not got far enough in my development to be sure. I think it's a good patch but I wouldn't merge just before a release...

### CODE REVIEW

**Comment by folletto** [comment]
Wow. Thanks! We'll check asap. :D

**Comment by Simbul** [comment]
We'll give it a run and do some testing to make sure nothing breaks.
Before we can do that, could you update the code to reflect the latest `master`? Merging in your JSON pull request has obviously created conflicts with this one :)

**Comment by Simbul** [comment]
Btw, have you had a chance to test whether push notifications still work after this change?

**Comment by sdarlington** [comment]
I'll try to isolate the changes from my master branch.

I've not been able to test push notifications yet. Now that I think about it, it might need some work -- when does the event loop end? Maybe we need to keep a synchronous option?

**Comment by folletto** [comment]
Hi @sdarlington 
We are very near to the 4.1 release right now, with MagRocket in beta and no issues left... apart from this one.
We'd love to include it... but since you were on it we want to ask you first what's the progress status. :)

Otherwise not big deal, we'll just move this pull request to the next version. :)

Thanks! :D

**Comment by sdarlington** [comment]
Personally I think this is a risky change to put in just before a release, so I think postponing to the next version would be the best bet. Also, I want to test with the push notifications (since I didn't last time) and am unlikely to get the time to do that before the weekend.

**Comment by folletto** [comment]
Well we would have tested it, but I prefer to judge from the perspective of the actual person that coded it, that's why I asked. Thanks! :D

We're looking forward to it. ;)

**Comment by Simbul** [comment]
4.1 is now out, so I think it's time to come back to this pull request ;)

@sdarlington have you had any chance to test with Push notifications?

**Comment by sdarlington** [comment]
Not yet. It's now next on my TODO...

**Comment by sdarlington** [comment]
I merged back to origin/master and fixed so that it will "download in the background."

**Comment by folletto** [comment]
Great! We'll check soon! :)

**Comment by Xm4s** [comment]
Ok, I've given four pull request a test run and the background downloads works like a charm during the normal app lifecycle.

However, when I try sending  a push notification the app freeze completely.
I've tried with the app opened (both foreground and background states) and closed, the result is the same.

I manage to make the push notification handling work correctly when the app is opened by wrapping up the content of the method [applicationWillHandleNewsstandNotificationOfContent:contentName] in the AppDelegate in a callback of the refresh call made there.

Even with this change if the app is closed push notification aren't handled correctly; to be more precise the application gets the notification, start the handling, make a refresh call ... but its callback is never called back.

Could you please check these unexpected behaviours?
As soon as everything work we'll be glad to merge your pull request in :)

**Comment by sdarlington** [comment]
Okay, I checked the following four scenarios and (as far as I can tell) it behaves the same as before in all cases:
- App in foreground, pressing refresh button
- App in foreground, receives push notification
- App in background, receives push notification
- App not running, receives push notification

The only one I'm not sure about is when it's suspended in the background. In this case it seems to _start_ running the code in `application:didReceiveRemoteNotification:` but stops after evaluating the `if` statement. It continues when the app is manually brought into the foreground. No code up to that point has been changed so I doubt I've changed its behaviour.

**Comment by Xm4s** [comment]
Hi! I manage to work on the notification issue with async networking some more and provide a fix for the app not running scenario.

The refresh call that's done in the newsstand notification handler point to a getShelfJSON call in the BakerAPI class;
Normally the call is made in a background thread while its callback is called on the main thread SO, if the main thread is unavailable (app not running), the callback won't be called till the app start ... and goodbye to background download.

I've put a simple check to execute all the code in background if the call to the getShelfJSON is already made in a thread different from the main one.

I'd like you to test it out and told me what you thinks, while it seems to work is a really delicate matter ... so if you please can help we'll be finally able to merge this into Baker :)

You can find all the commits on [this branch](https://github.com/Simbul/baker/tree/sdarlington-async-networking)

Thank you

**Comment by sdarlington** [comment]
How are you testing it? Background downloading worked as far as I could tell in my testing so I'm obviously missing something when I try!

**Comment by Xm4s** [comment]
In your last comment you said that:

> The only one I'm not sure about is when it's suspended in the background. In this case it seems to start running the code in application:didReceiveRemoteNotification: but stops after evaluating the if statement. It continues when the app is manually brought into the foreground.

We don't want the execution to stop because the app wouldn't be able to download new issue in response to a newsstand notification until the user open it up. That's what I've tried (and hopefully manage) to fix.

Now, when the app is closed or in background state a newsstand notification should awake it and have it download a new issue while remaining in background.

**Comment by Xm4s** [comment]
Ok, the pull request is finally merged into master :)
Thank you for your help and your contribution.

**Comment by sdarlington** [comment]
Excellent. Sorry I didn't get a chance to look at your change to my change... still on my TODO as I want to understand the Newsstand downloading stuff better.

**Pull request merged**
