### PR TITLE
Fix to allow use of Baker together with ARC-enabled code

### PR DESCRIPTION
**Pull request by vgrichina**
Method name should only start with 'init' if it is constructor.

### CODE REVIEW

**Comment by Simbul** [comment]
Just to be clear, is this the rule you are referring to?

> init methods must be instance methods and must return an Objective-C pointer type. Additionally, a program is ill-formed if it declares or contains a call to an init method whose return type is neither id nor a pointer to a super-class or sub-class of the declaring class (if the method was declared on a class) or the static receiver type of the call (if it was declared on a protocol).

(from the [ARC Specification](http://clang.llvm.org/docs/AutomaticReferenceCounting.html#family))

Were you getting any explicit errors with the old code?

**Comment by vgrichina** [comment]
Yep, this is the rule I refer to.

With old code compilation fails when Baker headers are included in ARC-enabled code.

**Comment by Simbul** [comment]
Merged into master, thanks for your contribution! :)

**Comment by vgrichina** [comment]
My pleasure :)

BTW, will you accept patches to make Baker better suited for use inside of other apps? Right now public interfaces sometimes are limited, e.g. I had to subclass to get access to protected fields to do some simple stuff like changing current page.

**Comment by folletto** [comment]
Yes.

Actually we were discussing exactly this point this evening, and it's our tracking Issue #59. :)
Our objective is to make Baker more modular, by moving it from being a RootViewController in an appropriate Class that could be easily included anywhere. :)

That's issue #59 ...would you like to help us by taking care of that - with our support, of course? :)

**Pull request merged**
