### PR TITLE
Open external links in a modal UIWebView

### PR DESCRIPTION
**Pull request by steiny2k**
When having many links in your book, getting kicked out of it and send to Safari every time is not very nice. Instead a modal view should be opened that quickly shows the page that the link refers to, and can easily be dismissed.

### CODE REVIEW

**Comment by ffranke** [comment]
;)

**Comment by folletto** [comment]
Thanks. :)
We'll test it out asap. :)

**Comment by mutador** [comment]
great solution...baker need this

**Comment by zenz** [comment]
It's quite well, but some bugs inside, firstly, it cannot change the orientation with book(such like landscape mode). and secondly, it will crash on iOS4.

For the first problem, just add

<pre>
- (BOOL)shouldAutorotateToInterfaceOrientation:(UIInterfaceOrientation)orientation
{
    if ((orientation == UIInterfaceOrientationPortrait) ||
        (orientation == UIInterfaceOrientationLandscapeLeft) ||
        (orientation == UIInterfaceOrientationPortraitUpsideDown)||
        (orientation == UIInterfaceOrientationLandscapeRight))
        return YES;
    
    return NO;
}</pre>

can solve it, for the second one, we need to check

**Comment by zenz** [comment]
OK, for the second problem, we got it. because presentViewController:animated:completion: is not available in iOS4.

So just change
[self presentViewController:myModalViewController animated:YES completion:nil];
to
[self presentModalViewController:myModalViewController animated:YES ];
in RootViewController.m is OK.

Also
 [self dismissViewControllerAnimated:YES completion:nil]; 
need to be change to 
[self dismissModalViewControllerAnimated:YES];

**Comment by mutador** [comment]
i always say the same(sorry), i use a solution in jquerymobile for this, that work well, but i prefer a integration in baker

see the las page of this, the buttom of suscripcion. (open an internal url whit a closed buttom)

http://itunes.apple.com/us/app/ohmygod-es-02/id499892763?l=es&ls=1&mt=8

**Comment by steiny2k** [comment]
Hi, everyone. Thanks for the feedback. 

For the iOS4 problem: I was aware of that. But since the dismiss/presentModalViewControllerAnimated functions are deprecated in iOS5 i thought i'd go with a solution that works for the future and omit support for iOS4. I don't know what your policy with Baker is. But if you want to support the older stuff too, then just change it like zenz proposed and it should work. If you want I can send another pull request with a solution that is working for iOS4.

For the orientation problem: I didn't think of that as our magazine is portrait only atm. But sure that has to be adressed. I think it shouldn't be a big problem. Just adding the landscape orientation in interface builder... let me see, what i can do, and i'll send you a new pull.

**Comment by steiny2k** [comment]
hm. ok. i'm kind of new to github. So closing and making a new pull request wasn't necessary i guess. well... 
see pull 325 for further discussion: https://github.com/Simbul/baker/pull/325

sorry for that.

**Comment by folletto** [comment]
No worries! :)
Thanks for that. :)

**Pull request closed without merging**
