### PR TITLE
iOS7 shelf text size

### PR DESCRIPTION
**Pull request by benoitchantre**
Display smaller font size for issue description and buttons.

capture decran 2013-09-10 a 18 15 52

### CODE REVIEW

**Comment by benoitchantre** [comment]
Closed because it's now integrated in the iOS7 branch.
@Simbul Did you noticed this PR?

**Comment by Simbul** [comment]
Yes, we did notice it, but it's against `master` as opposed to being against the `ios7` branch we're working on at the moment, which makes reading the diff pretty difficult.
We decided to have a look at it after merging `ios7` into `master`, but we still had to fix the font sizes in the meantime :wink:

**Comment by benoitchantre** [comment]
Sorry, I did something wrong with Github when I did the PR.
My solution is almost the same, except that I forgot the change the style for the price.
Otherwise, the only difference is that I have used `UIFontTextStyleSubheadline` for the title of the issue.

**Comment by benoitchantre** [comment]
@Simbul would you like I make a new PR or is it ok?

**Comment by folletto** [comment]
It's ok, we already implemented it in ec81af59df29488afcd04c406ff4b07d5836599d :)

**Pull request closed without merging**
