### PR TITLE
Fixes issue #642.

### PR DESCRIPTION
**Pull request by buildc0de**

### CODE REVIEW

**Comment by buildc0de** [comment]
Discovered an issue with iOS 5.1 where the webview doesn't finish loading a book on the very first read.

**Comment by Simbul** [comment]
Sorry, I'm a bit lost. Does this mean that the pull request fixes the orientation mismatch but it only works on iOS 6?

And was the iOS 5.1 bug introduced by the pull request or was it there from the beginning?

**Comment by buildc0de** [comment]
This does fix the orientation issue on iOS 5.x and 6 :-) But there is a new side issue on 5.x where the app seems to get stuck at -buildPageDetails on opening a book for the very first time...

**Comment by Simbul** [comment]
Thanks for the clarification :)

**Comment by buildc0de** [comment]
Oh, it looks like what I'm seeing in 5.x is related to issue #587.

**Comment by Simbul** [comment]
Is this pull request still relevant, or has it been superseded by one of the other pull requests you submitted? :)

**Comment by buildc0de** [comment]
Yep, still relevant.
This one fixes the orientation mismatch issue while the other requests take care of the remaining weirdness I was seeing :-)

**Comment by Simbul** [comment]
Tested on iOS 5.x and it does indeed fix the issue. However, it crashes when opening a book twice.

Steps to reproduce:
1. Consider a book with `"orientation": "landscape"`
2. While in portrait mode, open the book
3. The orientation is correctly rotated to landscape
4. Go back to shelf
5. Rotate the device to bring it back to portrait
6. Open the same book again
7. Crash

**Comment by buildc0de** [comment]
I think you might be seeing our old friend issue #643 :-) I do see the crash while in this branch. But if I merge the current master, then it is no longer there...

**Comment by Simbul** [comment]
I have tested it after locally merging your branch into master, so your fix was included.
I may mention though that my test was on an iPad1, so that might put certain constraints on memory size and processing power ;)

**Comment by buildc0de** [comment]
Just to clarify, issue #643 was fixed in your commit 3228d83 :-) Perhaps, you could double-check that it's part of your current app build... I definitely can't reproduce the crash in the Simulator (5.x and 6.x).

**Comment by Simbul** [comment]
Tested by @Xm4s on iOS 5.1 simulator with no issues. I think it's good to merge.
Thanks!

**Pull request merged**
