### PR TITLE
Localization

### PR DESCRIPTION
**Pull request by benoitchantre**
Here's an improvement to handle Localizations.

Now, you can add a new localization with Xcode and it will create automatically the appropriate localized folder /

Here's the result when you add a new localization

In Xcode
Capture d e cran 2013-01-21 a 09 59 42

Capture d e cran 2013-01-21 a 09 59 53

In the finder:
Capture d e cran 2013-01-21 a 10 06 25

Note: at the moment, no new localization added. Screen captures are provided to see what happen when you add a new localization.

### CODE REVIEW

**Comment by benoitchantre** [comment]
I think it would be great to have a page on the wiki that explains how to contribute to localize the app.
Some screen captures of a neutral app could help translators in their work, they will see the strings in context and will be able to provide a more accurate work.

**Comment by folletto** [comment]
Wanna create it? ;)

**Comment by benoitchantre** [comment]
If you find my english good enough, I can create it.
I can describe how to make a new localization, but I don't know the ideal process to submit them and to maintain them when new features are added.
Is there an easier than to make a fork and to submit a pull request?

**Comment by folletto** [comment]
This part is perfect (fork/pull request).
I mean the documentation part: just add a page on the wiki and we'll go ahead from there. :)

**Comment by benoitchantre** [comment]
I have create a page "Add a new localization", but I don't see it in the Wiki.

Screen captures will come later, I can't illustrate the strings related to the newsstand mode, because I haven't yet tested that mode.

**Comment by Simbul** [comment]
It's here: https://github.com/Simbul/baker/wiki/Add-a-new-localization

You need to link to it from the homepage to make it easier to reach ;)

Alessandro

**Comment by benoitchantre** [comment]
No problem, but maybe it's better to wait that the pull request is accepted?

**Comment by benoitchantre** [comment]
Thanks, that was my first pull request, i'm happy to contribute to this project.
The main page of the Wiki is updated with a link to "Add a new localization"

**Pull request merged**
