### PR TITLE
Open external links in a modal UIWebView

### PR DESCRIPTION
**Pull request by steiny2k**
A new pull request. Should address the problems mentioned in https://github.com/Simbul/baker/pull/324.

It works now with iOS4 and it supports orientation changes. Also the license header was changed to the Baker standard header.

### CODE REVIEW

**Comment by folletto** [comment]
Hi @steiny2k! :)

I tested it right now and it works great!

However we can't sign this feature as complete unless we add a couple more features, that are a must for an add-on browser like this:
1. The back/forward navigation: I saw the xib and it should be as simple as adding a couple of buttons and associating the two UIWebView actions.
2. A button to Open in Safari, because with this we are basically blocking that, and we still need to give that possibility to our users.

Do you think you could add these yourself? :)

**Comment by steiny2k** [comment]
Hi thanks for the feedback. Yeah sure. I'll do it in the next days :)

**Comment by folletto** [comment]
AWESOME. :)

Thanks. :)

**Comment by steiny2k** [comment]
The last commit should include the forward/backwards-buttons and the "open in Safari" button. However I have a strange behaviour in the simulator (can't test on native devices atm), where switching back to the app renders a black screen during the animation. It seems like the screenshot for the fast app switching isn't generated. Any ideas why this happens, and how i can address that?
Or maybe it's just something weird in the simulator here. I'm not sure. Please check it :)

**Comment by folletto** [comment]
That was quick! We'll test. :)

**Comment by bahmet** [comment]
guys, how can i enable and disable this option. is there any command similar to target blank...
 a href="http://www.facebook.com/aaaaa" target="_blank">

i have links to web page facebook and twitter pages and load time is not satisfying for me.

**Comment by folletto** [comment]
What do you mean? This isn't included yet. :)

**Comment by bahmet** [comment]
ok, i have some strange behaviors on my project.
i added some links on the page which goes to other pages. this does not work. however same links exist in the TOC but it works.
i added an external link on a page but it opens in the app not in the safari. while i was searching here i found this topic and guessed it is related to my problem.  is it ?? :)
 do you have any opinin why my links do not work as i wanted. BTW these links work on my computer via safari. however does not work in ipad via safari....
i need urgent help since i almost finished my project :))

**Comment by steiny2k** [comment]
well thanks @bahmet for your input. I now made the "open modally" optional with the last commit. Now you may use the following referrers and achive different behaviour:
- **referrer=ExternalBaker**: opens the link in Safari as it was before
- **referrer=ModalBaker**: opens the link in the new modal UIWebView but also allows the user to go to Safari if he wants to
- _no referrer_: opens the link in the local WebView where the book is currently rendered (I don't know if this is desirable in any situation. Can't think of any...)

Now to the problem you describe: for opening a link in safari with the current master branch add the referrer=Baker to your link (http://example.com/?referrer=Baker). For the internal links referring another page in the book, i don't actually know, why it does not work for you. If it works in the TOC, it should work in the usual book pages as well.

Using the target="_blank" attribute is not possible unfortunately as we only have the URL at the point in the code where this decision where to open the link is to be made. So using these _magic strings_ in the URL is actually a clever hack ;)

**Comment by bahmet** [comment]
@steiny2k  woww very fast solution..
so, how can i use this. should i copy your rootviewcontroller.m to my baker project and use the referrer like a href="http://www.facebook.com/aaaaa?referrer=externalbaker

**Comment by steiny2k** [comment]
Well, there is more changes than just the `rootviewcontroller.m` file. Best thing would be you check out my `master` branch of baker from https://github.com/steiny2k/baker. It is basically the current master branch from simbul/baker but with the modal UIWebView added. So basically all the stuff that lives inside this pull request.

Then you should be able to use this referrerr-scheme as i described in my previous comment. :) If necessary you can also adapt change the _magic strings_ by editing the `URL_OPEN_MODALLY` and `URL_OPEN_EXTERNAL` constants in the `RootViewController.m`

**Comment by folletto** [comment]
@bahmet Please, as I said before this thread doesn't refer to your problem. This discussion isn't included yet so you can't have used it at all. 

Please read this: https://github.com/Simbul/baker/wiki/Managing-links-and-urls and if you still have problems please open a new issue.

@steiny2k That's an issue with the main branch, we need to discuss this separately, adding features isn't always the right answer. ;)
There's no need to add additional flags on the dev side, it's solved with a link in the UI as I said above: "2. A button to Open in Safari". If that's implemented, we don't need any additional flag code-side. We need to discuss this.

His problem is different and doesn't refer to this issue. :)

**Comment by steiny2k** [comment]
Yeah most probably you're right. But letting the book designer decide whether to open a link directly in Safari or modally might also be a good idea, don't you think? But you can do as you like. Just leave out the last commit when pulling it in.

**Comment by folletto** [comment]
We need to review that. I'm not entirely sure, as it will create inconsistencies in the user interaction with the platform. It's important to allow the user to go to Safari - that's why we have the button - but creating two paths might create more disorientation and is definitely one more complex piece for the developers to manage.

Basically every app out there handles this thing in one and only one way, that's not by chance. ;)

**Comment by folletto** [comment]
@bahmet Please, open a separate issue. Please. Really. Please. :(

**Comment by folletto** [comment]
Ok, we merged the request, including the last change.

We are going to apply a couple of modifications:
1. The two strings are going to be `referrer=Baker` and `referrer=Safari` to open modally and in Safari respectively.
2. We are going to do a little rework on the buttons (text, position, look) to see what fits better.

Huge thanks. :)

**Comment by folletto** [comment]
Ok, we switched that to a more standard black, already pushed to MASTER. 

There are three things:
1. BUG: Unfortunately, we found a bug: when you are in modal view, and rotate the iPad, and then close the modal, then the navigation is broken until you rotate the iPad again. It's probably because the modal view doesn't call our rotate function.
2. BUG: The status bar behaves weirdly (double tap after the modal WebView is open).
3. FEATURE: It's probably better if we can switch from XIB to direct code. We found a nice project here: https://github.com/akosma/nib2objc that has ready a downloadable GUI to ease the transition.

We're looking into these now. :)

**Comment by folletto** [comment]
Ok, I opened the separate issues to track them. :)

**Comment by steiny2k** [comment]
Hi, I'm a bit concerned with the use of the action-button to open the site in safari. I think this button should only be used when creating a action-view and allowing the user to choose from an action to perform (i.e. open in Safari, post link to Twitter, E-Mail URL or stuff like this). See the [iOS Human Interface Guidelines](https://developer.apple.com/library/ios/DOCUMENTATION/UserExperience/Conceptual/MobileHIG/UIElementGuidelines/UIElementGuidelines.html#//apple_ref/doc/uid/TP40006556-CH13-SW33) table 7-2. It says "Open an action sheet that allows users to take an application-specific action".

As long as we don't allow users to choose from such an action sheet, maybe we should write explicitly on the button, what it will do (open in safari).

**Comment by Simbul** [comment]
Generally speaking, I agree with you.

In fact, that's where we want to head with that button. It's only a matter of putting out the minimal possible implementation first and enhancing it later.

**Comment by Dreeke** [comment]
I am running into the following problem with this implementation. I have setup a link on a page that I used to open within the books webview. In other words, without referrer. This is an online questionnaire and I would like for it to feel integrated within the app. It does indicate to the user that an internet connection is required.

This was working perfectly before apart from having no back and forward buttons.

This link is using javascript to submit a form when a user clicks the link. The form has a hidden field that passes a value that we need to log the user automatically in.

With the new commit after having stumbled upon this thread when searching how to tackle the back and forward buttons issue the form doesn't seem to function properly anymore ( when using a referrer, both Baker or Safari - does work without referrer ). The value we need to pass to bypass the 1st login page doesn't register somehow and we are faced with a login screen.

The code I am using is:

<script type="text/javascript">
            function submitform()
            {document.forms["test"].submit();}
            </script>
        <form action="http://website.com/?referrer=Baker" method="post" id="test">
            <input type="hidden" maxlength="255" name="some field name" value="our login value"/>
            <a href="javascript: submitform()">Take the test //</a> 
        </form>
</script>


Any suggestions or ideas?

**Comment by folletto** [comment]
I don't get exactly what are you trying to do. Let me see:
1. You open a site within Baker itself (no referrer)
2. You have a form there
3. The form... does what exactly? What should it do and what happens instead? What are you using to trigger it?

**Comment by Dreeke** [comment]
The form posts to an url, passing a field with a value that allows us to automatically login. The idea is to save the user from manually having to enter a certain value. 

What is not happening now is when using a referrer, which I would like to do, the form submit doesn't seem to pass the value and we are taken to the default starting page instead of the desired page.

**Comment by Dreeke** [comment]
Just to be clear, when I don't use a referrer it is working

**Comment by folletto** [comment]
Ok, let's see, another couple of questions:
1. What's the url in the `POST=""` attribute?
2. What's the url where are you landing instead?

Just to be completely clear: it doesn't open the slider with the new Baker internal browser, correct?

**Comment by Dreeke** [comment]
Just sent you a PM with the answers to 1 and 2. Not sure what you mean with the 'slider'.

**Comment by folletto** [comment]
The "slider" is the panel that now opens when you have a link with "referrer=Baker" :)
Like when you touch the logo on the first page of the example book. :)

**Pull request merged**
