### PR TITLE
Added info button to Shelf navigation bar.

### PR DESCRIPTION
**Pull request by freney**
On tapping the info button, we display an HTML popover (iPad) or a new view (iPhone) for custom app info. Text for the popover/view is sourced from info.html.

This addition can be seen in The Briefing app, cf. #991.

### CODE REVIEW

**Comment by fturner19** [comment]
Awesome!

**Comment by folletto** [comment]
This sounds great! Thanks! :D

**Comment by Simbul** [comment]
Just merged this in. Thanks for the contribution!

**Comment by freney** [comment]
Super. No probs.

**Pull request merged**
