### PR TITLE
Fix issue 1137: color of icons in the modal view

### PR DESCRIPTION
**Pull request by benoitchantre**
Use the same color that is used in the Navigator Bar.

### CODE REVIEW

**Comment by benoitchantre** [comment]
This fix change the default color under iOS6 too.
Maybe it's better to keep the default color under iOS6.
What do you think @folletto ?

**Comment by folletto** [comment]
Hello! We tested it, and definitely you're right: on iOS6 should keep the default formatting, while in iOS7 should use the color. Could you do that? :)

**Comment by benoitchantre** [comment]
Yes, let me a few minutes.

**Comment by benoitchantre** [comment]
I think everything is ok.

**Comment by folletto** [comment]
Yep! Awesome. :)

**Comment by mbayona** [comment]
Amazing work!! 

I do have a quick question:  As I try to use the Standalone option, when I run the project I do get a screen (Baker Shelf) with the two options of two different issues of my magazine (as I expect).  However, the spaces for the images to show individual icons for the issues are blank.  Where do I place the images for these icons to show the proper images?

Thanks for the help...

Miguel

**Comment by benoitchantre** [comment]
@mbayona, please open a separate issue for that and follow the instructions in [problems and debugging](https://github.com/Simbul/baker/wiki/Problems-and-Debugging). Have a look at the [HPub specification](https://github.com/Simbul/baker/wiki/hpub-specification), you probably didn't set properly the cover property in `book.json`

**Pull request merged**
